# Generated by Django 3.2.8 on 2021-11-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('warehouse_size', models.FloatField()),
                ('status_warehouse', models.CharField(default='Not active', max_length=15)),
                ('warehouse_number', models.CharField(max_length=3)),
                ('cost_per_month', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13)),
                ('api_key', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(default='user', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.CharField(max_length=145)),
                ('building_idbuilding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_warehouse.building')),
                ('user_iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_warehouse.users')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_warehouse.users')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderSum', models.FloatField()),
                ('LeaseStartDate', models.DateField()),
                ('LeaseEndDate', models.DateField()),
                ('active_status', models.BooleanField(default=0)),
                ('building_idbuilding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_warehouse.building')),
                ('personal_area_idpersonal_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_warehouse.personalarea')),
            ],
        ),
    ]
